version: 2
jobs:
        build:
                docker:
                        - image: debian:stretch

                steps:
                        - checkout
                        - run:
                                name: Greeting
                                command: echo "Hello, world"

                        - run:
                                name: Print current time
                                command: date

workflows:
        version: 2
        build_stuff:
                jobs:
                        - build
