version: 2
jobs:
        build:
                docker:
                        - image: debian:stretch
                steps:
                        - checkout
                        - run:
                                name: Greeting
                                command: echo "Hello, world!"

        print_date:
                docker:
                        - image: debian:stretch
                steps:
                        - checkout
                        - run:
                                name: Print current time
                                command: date

        echo_foo:
                docker:
                        - image: debian:stretch
                steps:
                        - run: echo "foo"

workflows:
        version: 2
        build_stuff:
                jobs:
                        - build
                        - print_date
                        - echo_foo
