version: 2
jobs:
        build:
                docker:
                        - image: debian:stretch
                steps:
                        - checkout
                        - run:
                                name: Sleep 15s
                                command: sleep 15s
                        - run:
                                name: Greeting
                                command: echo "dHello, world!"

        print_date:
                docker:
                        - image: debian:stretch
                steps:
                        - checkout
                        - run:
                                name: Print current time
                                command: date

        echo_foo:
                docker:
                        - image: debian:stretch
                steps:
                        - run: echo "foo"

workflows:
        version: 2
        build_stuff:
                jobs:
                        - build
                        - print_date
                        - hold_for_approval:
                                type: approval
                                requires:
                                        - build
                        - echo_foo:
                                requires:
                                        - hold_for_approval

        my_scheduled_workflow:
                triggers:
                        - schedule:
                                cron: "58 0 * * *"
                                filters:
                                        branches:
                                                only:
                                                        - master
                jobs:
                        - build
                        - print_date
                        - echo_foo:
                                requires:
                                        - build
